In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_csv('data/Social_network_Ads.csv')

In [3]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
X = dataset.iloc[:, [1, 2, 3]].values
y = dataset.iloc[:, 4].values

__Encoding data__

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder = LabelEncoder()
X[:, 0] = label_encoder.fit_transform(X[:, 0])
onehot_encoder = OneHotEncoder(categorical_features=[0])
X = onehot_encoder.fit_transform(X).toarray()

__Split dataset into train and test data__

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

__Feature Scaling__

> __Naive Bayes__

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [10]:
y_pred = nb_classifier.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[66,  2],
       [ 6, 26]])

> __Decision Tree__

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [14]:
dt_classifier = DecisionTreeClassifier(criterion='entropy', random_state=13)

In [15]:
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=13,
            splitter='best')

In [16]:
y_pred = dt_classifier.predict(X_test)

In [17]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[63,  5],
       [ 2, 30]])

> __Random Forest__

In [18]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
rf_classifier = RandomForestClassifier(n_estimators=20, criterion='entropy', min_samples_split=4)

In [47]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=4,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [48]:
y_pred = rf_classifier.predict(X_test)

In [49]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[64,  4],
       [ 5, 27]])

In [50]:
y_pred = rf_classifier.predict(X_train)

In [51]:
cm = confusion_matrix(y_train, y_pred)
cm

array([[182,   7],
       [  5, 106]])